version: '3.8'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      - minio
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
      - bonus_vol:/var/www/bonus
    networks:
      - inception_net
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - inception_net
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/html
      - cache:/data
    networks:
      - inception_net
    env_file:
      - .env
    restart: always
#-----------------Bonus----------------#
  redis:
    container_name: redis
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
    networks:
      - inception_net
    env_file:
      - .env
    restart: always
  
  ftp:
    container_name: ftp
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes: 
      - wordpress_vol:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    expose:
      - 8080
    networks:
      - inception_net
    volumes: 
      - wordpress_vol:/var/www/html
    restart: always

  static_webpage:
    container_name: static_webpage
    build:
      context: ./bonus/static_webpage
      dockerfile: Dockerfile
    volumes: 
      - bonus_vol:/var/www/bonus
    networks:
      - inception_net

  minio:
    container_name: minio
    build:
      context: ./bonus/minio
      dockerfile: Dockerfile
    expose:
      - 9003
      - 9004
    volumes:
      - minio_vol:/data/
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress_vol
      o: bind
  mysqldata:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysqldata
      o: bind
#-------------------bonus----------------volumes
  cache:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/cache
      o: bind
  bonus_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/bonus_vol
      o: bind
  minio_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/minio_vol
      o: bind

networks:
  inception_net:
    name: inception_net