version: '3.8'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      - minio
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
      - bonus_vol:/var/www/bonus
    networks:
      - inception_net
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - inception_net
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/html
      - cache:/data
    networks:
      - inception_net
    env_file:
      - .env
    restart: always
  
  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
    networks:
      - inception_net
    env_file:
      - .env
    restart: always
  
  ftp:
    container_name: ftp
    build:
      context: ./ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes: 
      - wordpress_vol:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - inception_net
    volumes: 
      - wordpress_vol:/var/www/html
    restart: always

  static_webpage:
    container_name: static_webpage
    build:
      context: ./static_webpage
      dockerfile: Dockerfile
    volumes: 
      - bonus_vol:/var/www/bonus
    networks:
      - inception_net
  
  minio:
    container_name: minio
    build:
      context: ./minio
      dockerfile: Dockerfile
    expose:
      - 9003
      - 9004
    volumes:
      - minio_vol:/data/
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

volumes:
  wordpress_vol:
  mysqldata:
  cache:
  bonus_vol:
  minio_vol:

networks:
  inception_net:
    name: inception_net